version: '3.4'

services:
  identityserver.api:
    container_name: identityserver-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5100:80"
      - "7100:443"
  identityserver.db:
    container_name: identityserver-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=IdentityServerDb
      - POSTGRES_PASSWORD=Password*-1
    ports:
      - 5432:5432
    volumes:
      - identityserverdb_volume:/var/lib/postgresql/data
