version: '3.4'

services:
  identityserver.api:
    image: ${DOCKER_REGISTRY-}identityserverapi
    build:
      context: .
      dockerfile: src/Presentation/IdentityServer.Api/Dockerfile
  identityserver.db:
    image: postgres

volumes:
  identityserverdb_volume: